---
- hosts: all

  tasks:
    - name: Install shiny
      command: sudo apt-get install gdebi-core
    - name: download shiny server
      command: wget -O shiny-server.deb http://download3.rstudio.org/ubuntu-12.04/x86_64/shiny-server-1.3.0.403-amd64.deb
    - name: Use GDebi to install the file
      command: sudo gdebi shiny-server.deb
